ooni/spec

test-helpers/th-006-reverse-traceroute.md
Towards https://trac.torproject.org/projects/tor/ticket/7414
=> Added reverse traceroute test helper specification

test-specs/ts-012-lantern.md
Adds Lantern test specification
=> Add draft of lantern test specification

oonib.md
When uploading JSON it's not a string, but it's a JSON object.
=> [oonib specification] clarify the meaning of content key

data-formats/df-000-base.md
It's not necessarily the user. Discussed with @hellais.
=> update(000-base.md): clarify annotations generator

test-specs/ts-018-whatsapp.md
Closes: https://github.com/TheTorProject/ooni-spec/issues/101
=> Fixes to the spec about the whatsapp test

data-formats/df-000-base.md
See also #113. Discussed with @hellais.
=> df-000-base.md: clarify test_helper_name

backends/bk-001-ooni-backend.md, backends/bk-003-collector.md
=> collector: clarify software_{name,version} meaning

nettests/ts-007-http-invalid-request-line.md
Related bug report: https://github.com/measurement-kit/measurement-kit/issues/1823
=> HIRL: specify behaviour on binary response

backends/bk-003-collector.md
Make really sure that it's very clear what to do when resubmitting.
=> bk-003-collector.md: further clarify resubmission

nettests/ts-017-web-connectivity.md
=>  web-connectivity: document case where hostname is an IP address

data-formats/df-001-httpt.md
=> df-001-httpt.md: document that header values may be binary

nettests/ts-015-psiphon.md
=> psiphon: document new implementation

nettests/ts-020-telegram.md
Related to https://github.com/ooni/probe-engine/pull/207
=> telegram: add agent and queries fields

nettests/ts-015-psiphon.md
=> Show psiphon test possible conclusions in a table

nettests/ts-023-tor.md
* master issue: https://github.com/ooni/probe-engine/issues/226
* implementation: https://github.com/ooni/probe-engine/issues/227
=> ts-023-tor.md: document the new tor test

nettests/ts-023-tor.md
See the following PR for more context:
https://github.com/ooni/sysadmin/pull/424
=> Explain how we derive the id of an input.

nettests/ts-024-sni-blocking.md
Part of https://github.com/ooni/probe-engine/issues/388
=> ts-024-sni-blocking.md: use example.com as test helper

nettests/ts-024-sni-blocking.md
See https://github.com/ooni/probe-engine/issues/309
=> ts-024-sni-blocking.md: better document design choices

nettests/ts-022-ndt.md
Closes https://github.com/ooni/probe-engine/issues/259
Closes https://github.com/ooni/probe-engine/issues/251
=> nettests: write spec for ndt7

nettests/ts-022-ndt.md
Closes https://github.com/ooni/probe-engine/issues/538
=> ts-022-ndt.md: explain more obstacles preventing removing IPs from NDT

data-formats/df-008-netevents.md, data-formats/df-009-tunnel.md, nettests/ts-021-dash.md, nettests/ts-022-ndt.md
Part of https://github.com/ooni/probe-engine/issues/533
=> Document the fields present when we're using a tunnel

data-formats/df-007-errors.md
Introduced in https://github.com/ooni/probe-engine/pull/682
Part of https://github.com/ooni/probe-engine/issues/646
=> df-007-errors.md: document the interrupted error

nettests/ts-023-tor.md
Companion PR: https://github.com/ooni/probe-engine/pull/720
=> ts-023-tor.md: document private bridges handling

data-formats/df-007-errors.md
Part of: https://github.com/ooni/probe-engine/issues/55
=> df-0070-errors.md: document http_request_failed

nettests/ts-018-whatsapp.md
While at it, fix JSON formatting.
Part of https://github.com/ooni/probe-engine/issues/740
=> ts-018-whatsapp.md: further clarify the text

data-formats/df-007-errors.md
Part of https://github.com/ooni/probe-engine/issues/763
=> df-007-errors.md: document json_parse_error

nettests/ts-017-web-connectivity.md
Part of https://github.com/ooni/probe-engine/issues/810.
See https://github.com/ooni/probe-engine/pull/839 for explanation.
=> ts-017-web-connectivity.md: document that blocking could also be false

README.md
=>  Spelling grammar

nettests/ts-026-riseupvpn.md
This spec goes along with https://github.com/ooni/probe-engine/pull/978
Please comment if, for whatever reason, this should be changed.
=> RiseupVPN spec

nettests/ts-026-riseupvpn.md
outcome of code review here: https://github.com/ooni/probe-engine/pull/978#discussion_r510728966
=> define riseupvpn provider api error values

nettests/ts-026-riseupvpn.md
another result of the PR review process here: https://github.com/ooni/probe-engine/pull/978#discussion_r510726605
=> remove redundant riseupvpn prefixes from json

nettests/ts-028-dnscheck.md
See https://github.com/ooni/probe-engine/pull/1140
=> feat(ts-028-dnscheck): document valid addresses for domain

backends/bk-003-collector.md
This diff contains changes that are consistent with the behaviour of
the existing collector, which has been recently rewritten by @FedericoCeratto.
I think we could possibly further simplify this document, but for now my
main priority was to clearly mark the close report operation as legacy, as
well as to stop documenting single measurement submission, which has
not been implemented so far and won't probably be implemented ever.
This occurred to me while performing cleanups in ooni/probe-engine
as part of https://github.com/ooni/probe-engine/pull/1145.
=> fix(collector): document the existing collector

nettests/ts-029-signal.md
xref: https://github.com/ooni/probe-cli/pull/230
Reference issue: https://github.com/ooni/probe-engine/issues/278
=> Add signal test specification

nettests/ts-030-torsf.md
See https://github.com/ooni/probe/issues/1565
=> doc: document ts-030-torsf

backends/th-007-nwcth.md, backends/th-007-websteps.md
See https://github.com/ooni/probe/issues/1729 and https://github.com/ooni/probe-cli/pull/431
=> th-007-websteps: websteps test helper spec

backends/th-007-websteps.md
Thanks to @hellais for providing readability fixes!
Reference issue: https://github.com/ooni/probe/issues/1733
=> th-007-websteps: changes from doc review

CONTRIBUTING.md
Reference issue: https://github.com/ooni/probe/issues/1670
=> CONTRIBUTING.md: refer to org wide guidelines

backends/th-007-websteps.md
See https://github.com/ooni/probe/issues/1740
Please, insert here a more detailed description.
=> fix(th-007-websteps): don't mention h3-29

nettests/ts-017-web-connectivity.md
=> fix(ts-017-web-connectivity.md): mention status_code and body_lenght may be -1

data-formats/df-007-errors.md
The file needed restructuring so that it is evident which errors are legacy and which can be encountered more recently. Also, a Markdown table was added to make it look more presentable.
=> Rearraging a data-format file

nettests/ts-032-tcpping.md
This diff documents the tcpping experiment.
=> feat: add tcpping experiment spec

nettests/ts-033-tlsping.md
See https://github.com/ooni/probe/issues/2088.
Please, insert here a more detailed description.
=> feat: introduce the tlsping experiment

nettests/ts-031-quicping.md, nettests/ts-034-simplequicping.md
See https://github.com/ooni/probe/issues/2091 (issue) and https://github.com/ooni/probe-cli/pull/717 (impl).
While there, ensure we remove the `oddity` from the JSON examples, since it's non standard and most likely we're going to remove oddities after community feedback (see https://github.com/ooni/probe/issues/2034).
=> feat: introduce the simplequicping experiment

nettests/ts-035-dnsping.md
See https://github.com/ooni/probe/issues/1987 (issue).
=> feat: introduce the dnsping experiment

nettests/ts-016-vanilla-tor.md, nettests/ts-030-torsf.md
This diff is the ooni/spec portion of a larger contribution that brings
back the vanilla_tor experiment to ooniprobe.
=> feat: re-implement the vanilla_tor experiment

nettests/ts-023-tor.md
See: https://github.com/ooni/sysadmin/pull/495
=> Add data analysis consideration related to the changing bridge ID

data-formats/df-002-dnst.md, data-formats/df-007-errors.md
See https://github.com/ooni/probe-cli/pull/765, where I identified
I needed to sync up spec with probe-cli.
=> formats: document dns errors and resolver types

nettests/ts-036-browser_web.md
This is a draft spec for ooni/probe-web: https://ooni.github.io/probe-web/
=> Add browser_web spec

nettests/ts-035-dnsping.md
Updated `dnsping` data format to conform with the new nettest.
=> doc(dnsping): update data format

data-formats/df-006-tlshandshake.md, nettests/ts-033-tlsping.md, nettests/ts-034-simplequicping.md
Updated `simplequicping` data format to conform with the new nettest
=> doc(simplequicping): update data format

nettests/ts-035-dnsping.md
Please, insert here a more detailed description.
=> dnsping: record delayed DNS response

.editorconfig, data-formats/df-000-base.md, data-formats/df-001-httpt.md, data-formats/df-002-dnst.md, data-formats/df-005-tcpconnect.md, data-formats/df-006-tlshandshake.md, data-formats/df-008-netevents.md
Part of https://github.com/ooni/probe/issues/2238
While there, add `.editorconfig`.
=> fix: sync with web_connectivity@v0.5 data format

nettests/ts-038-port-filtering.md
This is an experimental spec for the new port-filtering experiment
=> ts-038-port-filtering: introduce new experiment spec

nettests/ts-029-signal.md
This is related to: https://github.com/ooni/probe/issues/2344
=> Add information about the signal bug to the test spec

data-formats/df-006-tlshandshake.md
=> Add server_name to tls_handshake spec

nettests/ts-018-whatsapp.md
See https://github.com/ooni/probe/issues/2374
=> fix(whatsapp): stop measuring http://web.whatsapp.com/

nettests/ts-020-telegram.md
See https://github.com/ooni/probe/issues/2382
=> fix(telegram): stop measuring http://web.telegram.org/

backends/bk-005-ooni-run-v2.md, backends/bk-005-ooni-run.md
=> Add initial spec for OONI run

data-formats/df-008-netevents.md
See https://github.com/ooni/probe-cli/pull/1166
Part of https://github.com/ooni/probe/issues/2493
=> feat(netevents): mention bytes_received_cumulative

nettests/ts-029-signal.md
We trim down signal endpoints to increase robustness against endpoints churn.
=> signal: document trimming down endpoints

nettests/ts-017-web-connectivity.md
This diff updates the measurement algorithm description to describe Web Connectivity v0.5.
Part of https://github.com/ooni/probe/issues/2666
=> doc(web-connectivity): update measurement algo description

nettests/ts-017-web-connectivity.md
Closes https://github.com/ooni/probe/issues/2666
=> chore(web-connectivity): update examples

backends/bk-005-ooni-run-v2.md
See: https://github.com/ooni/probe/issues/2829
=> Update OONI Run v2 spec
