- data-formats/df-000-base.md
- test-specs/ts-014-psiphon.md
* add initial version of add psiphon test specification
* add ConnectionDone error in df-000-base.md. This error is triggered when the URL in a HTTP request is not found using psiphon
> add psiphon test specification

- informed-consent/data-policy.md
I wrote a Data Policy for OONI. All feedback welcome. :)
> created a data policy for OONI

- oonib.md
It is actually the converse. We may want to totally get rid of YAML.
> oonib.md: remove a lie

- informed-consent/inform-users-long.md
It probably should point to `/data` now.
> Broken link in `inform-users-long.md`

- test-specs/ts-007-http-invalid-request-line.md
Ref: https://github.com/measurement-kit/measurement-kit/issues/1416
> Add test_squid_cache_manager test to http invalid request line probing.

- test-specs/ts-017-web-connectivity.md
line 160: '...but the HTTP request either fails or we get back a HTTP response *that* contains a page we don't expect.'
> Added 'that' for clarity.

- test-specs/ts-010-captive-portal.md
I looked around for what Microsoft, Google, and Apple do for captive portal detection these days and wrote a test for it in measurement-kit here:
https://github.com/measurement-kit/measurement-kit/pull/1238
I'm proposing a different report format here.
> Update captive-portal spec

- techniques/tq-xxx-attempt-ecn.md
- techniques/tq-xxx-attempt-h2-upgrade.md
- techniques/tq-xxx-attempt-tfo.md
This pull request adds three techniques from [PATHspider](https://pathspider.net/):
* Detecting middleboxes through ECN induced connectivity failure
* Detecting middleboxes through TCP fast open induced connectivity failure
* Detecting middleboxes through H2 upgrade mechanism induced connectivity failure
This was worked on at the MAMI Project's Active Measurement Hackathon in Aberdeen, Scotland.
> Adds techniques from PATHspider

- nettests/ts-020-telegram.md
1. explicitly mention how the summary variables are computed, because that was left implicit
2. modify the spec to make it consistent with all existing implementations with respect to when we consider telegram to be blocked at the HTTP level (the previous wording was such that I could not decide what it meant). Both MK and ooni/probe-legacy start with setting Telegram blocked at the HTTP level and then unblock it if "successful". (I am profoundly skeptical that we can easily define success here without speaking the protocol, and without validating certificates, because in reality we may be speaking with any endpoint; also, in my limited tests, now Telegram does not respond with `501` anymore -- all of this tells us possible ways in which we can perhaps improve our Telegram implementation) …
> Fix telegram spec to increase clarity

- techniques/tq-034-block-udp.md
- techniques/tq-035-block-quic.md
With this PR I'd like  to raise the awareness of importance for measuring QUIC availability. QUIC is the new transport protocol based on UDP - if UDP is blocked, QUIC will be blocked as well. So naturally it makes sense to split those measurements and execute them sequentially one after the other.
This PR is serves as a starting point and  merely adds two new techniques (UDP and QUIC blocking)  but does not include nettest and data format specs. Although, both should be pretty straightforward to document.
If QUIC blocking technique is accepted, I believe we can approach the implementation iteratively: 
1. start with the nettest and data format descriptions;
2. update measurement-kit to execute the tests;
3. update probe tools to integrate new measurements;
4. send data to collector where …
> QUIC availability

- techniques/tq-012-traceroute.md
That's the note referring the example commited in https://github.com/TheTorProject/ooni-web/pull/265
> traceroute: add example capturing different filters with different goals

- nettests/ts-018-whatsapp.md
It's probably wise to mention this in the spec because it has impacts on
the data quality, because most tests now result into an anomaly.
Tracking issue: https://github.com/ooni/probe-engine/issues/341.
> ts-018-whatsapp.md: ack CIDR logic being broken

- nettests/ts-024-sni-blocking.md
Implemented at https://github.com/ooni/probe-engine/pull/391.
Part of https://github.com/ooni/probe-engine/issues/309.
> ts-024-sni-blocking.md: document result classification

- nettests/ts-024-sni-blocking.md
With @fortuna we had today a 1:1 meeting where we improved the design
of sni-blocking classification to make it easier to understand.
This diff implements the changes we agreed to apply.
Sibling of https://github.com/ooni/probe-engine/pull/397.
Part of https://github.com/ooni/probe-engine/issues/309.
> ts-024-sni-blocking.md: address @fortuna's feedback

- data-formats/df-000-base.md
- data-formats/df-001-httpt.md
* Fix the version numbers errors of base and httpt data formats introduced
by 3203a0426e9798d7f87ed5180a7ed4ff017a7a03
* Fix minor spelling typos
> Fix data formats versions and minor typos

- data-formats/df-007-errors.md
- nettests/ts-018-whatsapp.md
Specifically, say that WhatsApp web is reachable over HTTPS regardless
of the HTTP status code and that over HTTP we're happy if we get a
redirect to the correct location.
This is part of https://github.com/ooni/probe-engine/issues/740.
While there, remove the all endpoints option. We should test all the
endpoints to make a better statement on whether it's blocked.
(A single endpoint down is, in fact, a false positive.)
While there, explicitly say that the CIDR check is gone for good,
since it has not been working for quite some time now.
While there, mention all the parent data formats and specify the
toplevel structure in a more strict way.
> whatsapp: improve spec to reduce false positives

- nettests/ts-027-urlgetter.md
The documentation does not specify all the options because they are
poised to change over time. Let us document the spirit of the experiment
and the main supported input URLs, though.
Closes https://github.com/ooni/probe-engine/issues/1055.
> doc: document urlgetter

- data-formats/df-006-tlshandshake.md
- data-formats/df-008-netevents.md
- nettests/ts-017-web-connectivity.md
The related issue is https://github.com/ooni/probe-engine/issues/1157.
While there, I also lightly edited the specification to reference
existing data formats and to increase its adherence to the real
implementation we are using.
I look forward to further improve this specification as I continue
to work on the topic of improving Web Connectivity.
> fix(webconnectivity): document network events and tls handshakes

- nettests/ts-026-riseupvpn.md
introduce transport_status for a better filtering of false positive RiseupVPN nettest failures
part of https://github.com/ooni/probe/issues/1354
> reduce false positive rate in RiseupVPN tests

- nettests/ts-025-stun-reachability.md
1. the input MUST now be an URL
2. there is no default input anymore
See https://github.com/ooni/probe-cli/pull/539
> fix(stun): document changes in input handling

- nettests/ts-031-quicping.md
This refers to https://github.com/ooni/probe/issues/1994 and is related to https://github.com/ooni/probe-cli/pull/677.
The spec describes the new `quicping` experimental network test.
> ts-031-quicping: quicping spec

- data-formats/df-001-httpt.md
The `socksproxy` field is only set when a nettest uses a SOCKS proxy. This is different from the SOCKS proxy used to contact the backend. Clarifications have been added to `df-001-httpt.md`.
> df-001-httpt.md: clarify socksproxy field meaning

- nettests/ts-030-torsf.md
Added default_timeout field for the torsf measurement result for better understanding of users.
> Issue/2061 : torsf default timeout

- data-formats/df-006-tlshandshake.md
Added the endpoint address field to tls_handshake data format.
> tls_handshake: added ip address to tls_handshake data-format

- data-formats/df-000-base.md
Document the probe_network_name field.
@bassosimone can you check since when we have started to include this field in measurements?
> Add probe_network_name

- data-formats/df-002-dnst.md
In https://github.com/ooni/probe/issues/2029#issuecomment-1140805266, we
explained why calling it "netgo" would be incorrect.
In other words, we can get the platform's `getaddrinfo` as long as
we're not cross compiling. We do cross compile `ooniprobe`, actually
it's not even possible to cross compile it.
For increased accuracy, we should stop cross compiling `miniooni`
as well, so it would also directly use `getaddrinfo`.
This diff fixes at the same time ooni/probe-cli and ooni/spec
and we'll open two pull requests in parallel.
> netxlite: do not call netgo the CGO_ENABLED=0 resolver

- nettests/ts-023-tor.md
While there, move important information before the example output.
Reference issue: https://github.com/ooni/probe/issues/1986
> tor: document ntor AUTH mismatch

- nettests/ts-032-tcpping.md
- nettests/ts-033-tlsping.md
We want to avoid suggesting that a single TCP ping result could
contain more than one TCP connect attempt. Therefore, use a single
entry instead of using a list.
In the same vein, a TLS ping contains a TCP connect attempt plus
an optional TLS handshake. So, also there modify the spec to
use a single entry rather than a list for both TCP and TLS.
> doc(tcpping, tlsping): update data format

- data-formats/df-002-dnst.md
> dnst: document new fields

- PULL_REQUEST_TEMPLATE.md
- data-formats/df-002-dnst.md
This pull request documents more precise stdlib resolver naming that will benefit web_connectivity@v0.5.
See https://github.com/ooni/probe/issues/2238, https://github.com/ooni/probe/issues/2237, https://github.com/ooni/probe-cli/pull/885.
While there, fix the template for new PRs.
> doc(dns): more precise stdlib resolver naming

- data-formats/df-001-httpt.md
- data-formats/df-006-tlshandshake.md
- nettests/ts-034-simplequicping.md
See https://github.com/ooni/probe-cli/pull/946 where we also explain why we're doing this change.
Reference issue: https://github.com/ooni/probe/issues/2238
> refactor(datafmt): use "udp" instead of "quic"

- nettests/ts-039-echcheck.md
Adds spec for a new `echcheck` experiment that tests for interference of TLS handshakes with the Encrypted Client Hello (ECH) extension present.
> add echcheck experiment spec

- data-formats/df-005-tcpconnect.md
Example of a measurement showing this behaviour: https://explorer.ooni.org/m/20210101003640.413492_AR_telegram_ad086fbac780bdae
Please, insert here a more detailed description.
> df-005-tcpconnect: mention old probes setting failure to false

- nettests/ts-026-riseupvpn.md
This pull request syncs riseupvpn spec with ooniprobe 3.19.
Closes https://github.com/ooni/probe/issues/2563.
> doc(riseupvpn): sync with ooniprobe 3.19

- backends/bk-005-ooni-run-v2.md
We had a conversation today where we concluded to clearly mark some fields we're currently experimenting with as experimental. Obviously, we don't plan on changing them for the sake of change, but we also want to be careful about communicating in which areas we're still experimenting.
Part of https://github.com/ooni/ooni.org/issues/1384
> oonirunv2: flag experimental fields

- data-formats/df-006-tlshandshake.md
Closes https://github.com/ooni/probe/issues/1539 by clarifying the semantics of server_name.
> fix(df-006-tlshandshake.md): clarify server_name semantics

- nettests/ts-017-web-connectivity.md
In markdown, there should be just one top-level entry in a file.
To address this, create a title with the nettest name and then make sure all the other titles fall below one level.
Part of https://github.com/ooni/probe/issues/2666
(If I have time, I'll try to do some maintenance of all the nettest specs and implement similar changes, but for now I will only limit my boyscout-rules instincts to the spec I am editing.)
> fix(ts-017-web-connectivity): proper markdown

- nettests/ts-017-web-connectivity.md
I think the spec was lacking too much detail and did not explain to a technical user the big picture of what happens when they run Web Connectivity.
I know this choice is going to put more burden on the maintainer of the spec but I am the maintainer and I am happy about carrying this burden.
See https://github.com/ooni/probe/issues/2666.
> fix(web-connectivity): explain input more in detail

- nettests/ts-017-web-connectivity.md
The examples regarding the data format take lots of space and make reading the specification difficult possibly causing readers to miss important sections available near the end.
As a fix, move all the examples at the end in its own section.
See https://github.com/ooni/probe/issues/2666
> fix(web-connectivity): create examples section

- data-formats/df-008-netevents.md
the previous phrasing could induce to think that `t` is only measured in the case of failures.
> docs: try to be more precise about interval

- nettests/ts-020-telegram.md
This diff updates the telegram nettest spec to include the latest IP endpoints we measure as part of the test
> fix: synchronize telegram IPs with engine

- nettests/ts-040-openvpn.md
Add initial spec for the `openvpn` experiment.
This proposal supersedes a previous version (https://github.com/ooni/spec/pull/255).
ICMP Pings and URLGrabber over the tunnel are not included, this experiment just does OpenVPN handshakes at the moment.
> feat: add openvpn experiment spec

- data-formats/df-009-tunnel.md
- nettests/ts-040-openvpn.md
Modify spec to comply with the semantics of df-009-tunnel
> modify openvpn nettest specification to conform to df-009-tunnel
